### ISSUE TITLE
Sauce VS extension wont install for VS2013 Ult or VS2015 Ent

### ISSUE THREAD

**Issue by shawty** [iamkrillin/SauceDB#2]
I have both products installed, yet when I attempt to install the SauceDB class generation extension it fails claiming there are no applicable products for it to install into.

I suspect looking at the logs, that it may be looking only for a specific VS edition (2010?) and failing beacuse that's all it looks for.

This is the box produced:

![image](https://cloud.githubusercontent.com/assets/1876454/23459620/1c99e234-fe79-11e6-87a5-dbcbfd1a873c.png)

and this is the install log produced:

`01/03/2017 12:20:32 - Microsoft VSIX Installer`
`01/03/2017 12:20:32 - -------------------------------------------`
`01/03/2017 12:20:32 - Initializing Install...`
`01/03/2017 12:20:37 - Extension Details...`
`01/03/2017 12:20:37 - 	Identifier         : 2560de1c-b91e-4fd9-b6c6-9bc9e7208428`
`01/03/2017 12:20:37 - 	Name               : SauceClassGeneration`
`01/03/2017 12:20:37 - 	Author             : TheCodeHaven`
`01/03/2017 12:20:37 - 	Version            : 1.4`
`01/03/2017 12:20:37 - 	Description        : This extension will allow you to generate classes for use with SauceDB.  These files will then be added to your project in the following location <project>\SauceDB.  This extension will generate classsed based on an existing database schema and all datastores supported by SauceDB (SqlServer (password and ad auth), PostgreSQL, SQLite, and MySql) are supported here.  For more information and documentation see http://sauce.codeplex.com`
`01/03/2017 12:20:37 - 	Locale             : en-US`
`01/03/2017 12:20:37 - 	MoreInfoURL        : http://sauce.codeplex.com/`
`01/03/2017 12:20:37 - 	InstalledByMSI     : False`
`01/03/2017 12:20:37 - 	SupportedFrameworkVersionRange : [4.5]`
`01/03/2017 12:20:37 - `
`01/03/2017 12:20:37 - 	SignatureState     : Unsigned`
`01/03/2017 12:20:37 - 	Supported Products : `
`01/03/2017 12:20:37 - 		Microsoft.VisualStudio.Pro`
`01/03/2017 12:20:37 - 			Version : [11.0]`
`01/03/2017 12:20:37 - `
`01/03/2017 12:20:37 - 	References         : `
`01/03/2017 12:20:37 - 		-------------------------------------------------------`
`01/03/2017 12:20:37 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0`
`01/03/2017 12:20:37 - 		Name         : Visual Studio MPF 11.0`
`01/03/2017 12:20:37 - 		Version      : [11.0]`
`01/03/2017 12:20:37 - 		MoreInfoURL  : `
`01/03/2017 12:20:37 - 		Nested       : No`
`01/03/2017 12:20:37 - `
`01/03/2017 12:20:37 - Signature Details...`
`01/03/2017 12:20:37 - 	Extension is not signed.`
`01/03/2017 12:20:37 - `
`01/03/2017 12:20:37 - Searching for applicable products...`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Ultimate 2013`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Premium 2013 `
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Professional 2013`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Enterprise 2015`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Professional 2015`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio Community 2015`
`01/03/2017 12:20:37 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)`
`01/03/2017 12:20:37 - Found installed product - Global Location`
`01/03/2017 12:20:37 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.`
`   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)`
`   at VSIXInstaller.App.InitializeInstall()`
`   at System.Threading.Tasks.Task.InnerInvoke()`
`   at System.Threading.Tasks.Task.Execute()`

Is this an oversight, bug, or have I missed something?

Cheers
Shawty

**Comment by iamkrillin** [comment]
Thanks for bringing this to my attention.  I'll look into it tonight.

**Comment by shawty** [comment]
No probs.  If you need me to re-test, or want more info, just shout.

Shawty
