### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by rstelling** [iamkrillin/SauceDB#3]
Opened DataAccessV2.sln. Got errors about something Advantage not found so removed that project from the solution.  Now get several errors that 'IDataStore' does not contain a definition for 'TypeInformationParser'

**Comment by iamkrillin** [comment]
Hrm, I might have failed to check something in.  My apologies, I'll investigate this a bit later tonight

**Comment by rstelling** [comment]
Thanks for the quick response. I saw that I was able to compile what I
needed, the core and DataAccess.SQLLite. I will probably try out some calls
tomorrow or next  week. I'm glad for the wrapper, it was probably your post
on StackOverflow that lead me to the SauceDB package and the Microsoft and
SQLLite packages. I noticed the latter was in C++ and I didn't want to deal
with creating my own wrapper, just for experiments for my application.

**Comment by iamkrillin** [comment]
Should be good now, turn out, I did indeed fail to check a few things in
